# -*- coding: utf-8 -*-
"""mycaptain1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-D9jpfpE7ej-xNL28mnroXUBwIZYaWS
"""

import math
r=float(input("Input the radius of a circle: "))
print("The area of the circle with radius ",r," is ",(math.pi*r*r))

file_name=input("Input the Filename: ")
ext=file_name[-2]+file_name[-1]
if ext=="py":
  print("The extension of the file is:'python'")